// Generated by gencpp from file touch_set/OmniFeedback.msg
// DO NOT EDIT!


#ifndef TOUCH_SET_MESSAGE_OMNIFEEDBACK_H
#define TOUCH_SET_MESSAGE_OMNIFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace touch_set
{
template <class ContainerAllocator>
struct OmniFeedback_
{
  typedef OmniFeedback_<ContainerAllocator> Type;

  OmniFeedback_()
    : force()
    , position()  {
    }
  OmniFeedback_(const ContainerAllocator& _alloc)
    : force(_alloc)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _force_type;
  _force_type force;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::touch_set::OmniFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::touch_set::OmniFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct OmniFeedback_

typedef ::touch_set::OmniFeedback_<std::allocator<void> > OmniFeedback;

typedef boost::shared_ptr< ::touch_set::OmniFeedback > OmniFeedbackPtr;
typedef boost::shared_ptr< ::touch_set::OmniFeedback const> OmniFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::touch_set::OmniFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::touch_set::OmniFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::touch_set::OmniFeedback_<ContainerAllocator1> & lhs, const ::touch_set::OmniFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.force == rhs.force &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::touch_set::OmniFeedback_<ContainerAllocator1> & lhs, const ::touch_set::OmniFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace touch_set

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::touch_set::OmniFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::touch_set::OmniFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::touch_set::OmniFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::touch_set::OmniFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::touch_set::OmniFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::touch_set::OmniFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::touch_set::OmniFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9083ac4fd95494e94fbb0c0f90b6c00";
  }

  static const char* value(const ::touch_set::OmniFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9083ac4fd95494eULL;
  static const uint64_t static_value2 = 0x94fbb0c0f90b6c00ULL;
};

template<class ContainerAllocator>
struct DataType< ::touch_set::OmniFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "touch_set/OmniFeedback";
  }

  static const char* value(const ::touch_set::OmniFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::touch_set::OmniFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This is the force as estimated from the applied torques as well as the\n"
"# current end effector position of the robot arm\n"
"geometry_msgs/Vector3  force\n"
"geometry_msgs/Vector3  position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::touch_set::OmniFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::touch_set::OmniFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.force);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OmniFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::touch_set::OmniFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::touch_set::OmniFeedback_<ContainerAllocator>& v)
  {
    s << indent << "force: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.force);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOUCH_SET_MESSAGE_OMNIFEEDBACK_H
