# 请求响应的数据
string                   camSerialNum
uint32                   typeInfo
uint32                   frameNum
int64                    timeStamp
sensor_msgs/PointCloud2  pointCloud
---
# 回复响应的数据
std_msgs/Bool            result