// Generated by gencpp from file robot_set/TCPState.msg
// DO NOT EDIT!


#ifndef ROBOT_SET_MESSAGE_TCPSTATE_H
#define ROBOT_SET_MESSAGE_TCPSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot_set
{
template <class ContainerAllocator>
struct TCPState_
{
  typedef TCPState_<ContainerAllocator> Type;

  TCPState_()
    : header()
    , position()
    , velocity()  {
    }
  TCPState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , velocity(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _position_type;
  _position_type position;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::robot_set::TCPState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_set::TCPState_<ContainerAllocator> const> ConstPtr;

}; // struct TCPState_

typedef ::robot_set::TCPState_<std::allocator<void> > TCPState;

typedef boost::shared_ptr< ::robot_set::TCPState > TCPStatePtr;
typedef boost::shared_ptr< ::robot_set::TCPState const> TCPStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_set::TCPState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_set::TCPState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_set::TCPState_<ContainerAllocator1> & lhs, const ::robot_set::TCPState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_set::TCPState_<ContainerAllocator1> & lhs, const ::robot_set::TCPState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_set

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_set::TCPState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_set::TCPState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_set::TCPState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_set::TCPState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_set::TCPState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_set::TCPState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_set::TCPState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5fbf541e654dab38ddd37689024b1edc";
  }

  static const char* value(const ::robot_set::TCPState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5fbf541e654dab38ULL;
  static const uint64_t static_value2 = 0xddd37689024b1edcULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_set::TCPState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_set/TCPState";
  }

  static const char* value(const ::robot_set::TCPState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_set::TCPState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header  # 携带时间戳和参考坐标系ID\n"
"float64[] position   # TCP位置数组（x,y,z,rx,ry,rz）(m)\n"
"float64[] velocity  # TCP速度数组（x,y,z,rx,ry,rz）(m/s,rad/s)\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot_set::TCPState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_set::TCPState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TCPState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_set::TCPState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_set::TCPState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "velocity[]" << std::endl;
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      s << indent << "  velocity[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velocity[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SET_MESSAGE_TCPSTATE_H
